version: '3'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./dbdata:/var/lib/mysql
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 222:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.1.1-fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./wordpress/themes:/var/www/html/wp-content/themes/
      - ./wordpress/plugins:/var/www/html/wp-content/plugins/
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    restart: always
    ports:
      - 2222:80
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./wordpress/themes/docker-test-plugin:/var/www/html/wp-content/themes/
      - ./wordpress/plugins:/var/www/html/wp-content/plugins/docker-test-plugin
    networks:
      - app-network


volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge