version: '3'

services:

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

    wordpress:
      depends_on:
        - db
      image: wordpress:6.1.1-fpm-alpine
      container_name: wordpress
      restart: always
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: admin
        WORDPRESS_DB_PASSWORD: admin
        WORDPRESS_DB_NAME: wordpress
      volumes:
        - wordpress:/var/www/html
        - /
      networks:
        - app-network