version: '3'

services:

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./dbdata:/var/lib/mysql
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

    wordpress:
      depends_on:
        - db
      image: wordpress:6.1.1-fpm-alpine
      container_name: wordpress
      restart: always
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: admin
        WORDPRESS_DB_PASSWORD: admin
        WORDPRESS_DB_NAME: wordpress
      volumes:
        - wordpress:/var/www/html
        - ./wordpress/themes:/var/www/html/wp-content/themes/
        - ./wordpress/plugins:/var/www/html/wp-content/plugins/
      networks:
        - app-network

    webserver:
      depends_on:
        - wordpress
      links:
        - php
      image: nginx:1.15.12-alpine
      container_name: webserver
      restart: always
      ports:
        - 2222:80
      volumes:
        - wordpress:/var/www/html
        - ./nginx-conf:/etc/nginx/conf.d
      networks:
        - app-network

    php:
      build:
        ./php
      image: php:7.4-fpm
        # этот образ будет общаться с mysql
      links:
        - db
      volumes:
        - ./app:/var/www/html
      depends_on:
        - db
      networks:
        - app-network

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge